### ISSUE TITLE
Sha Aliases

### ISSUE THREAD

**Issue by tinder-aminghadersohi** [Tinder/GitQuery#2]
Would it be possible to have a top level object with sha aliases?
```
commits:
  - latest: 1a9f80ddec446aa9dd25714ecf15f66325cf9c53
    foobar: d25714ecf15f66325cf9c531a9f80ddec446aa9d
```
Then you can use the aliases instead of the sha for the protos
```
model:
  interact:
    network:
      apps:
        third_party.proto: latest
      api.proto: foobar
      network.proto: foobar
      send.proto: foobar
```
